using System.Text;

namespace DemoSourceGenerator;

public sealed class DemoCodeGenerator : ICodeGenerator
{
   public static readonly DemoCodeGenerator Instance = new();

   private static int _counter;

   public string? FileHintSuffix => null;

   public string Generate(DemoEnumInfo enumInfo, IReadOnlyDictionary<string, string> translations)
   {
      var ns = enumInfo.Namespace;
      var name = enumInfo.Name;

      var sb = new StringBuilder(@$"// <auto-generated />
#nullable enable

// generation counter: {Interlocked.Increment(ref _counter)}

using System.Collections.Generic;
using DemoLibrary;

{(ns is null ? null : $@"namespace {ns}
{{")}");

      sb.Append(@$"
   partial class {name}
   {{
      private static IReadOnlyList<{name}>? _items;
      public static IReadOnlyList<{name}> Items => _items ??= GetItems();

      private static IReadOnlyList<{name}> GetItems()
      {{
         return new[] {{ {String.Join(", ", enumInfo.ItemNames)} }};
      }}
   }}
{(ns is null ? null : @"}
")}");

      return sb.ToString();
   }

   public override bool Equals(object? obj)
   {
      return obj is DemoCodeGenerator;
   }

   public bool Equals(ICodeGenerator other)
   {
      return other is DemoCodeGenerator;
   }

   public override int GetHashCode()
   {
      return GetType().GetHashCode();
   }
}
